name: technical_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  chaleno: ^0.0.6
  cupertino_icons: ^1.0.2
  dio: ^4.0.5
  equatable: ^2.0.5
  fancy_shimmer_image: ^2.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_inappwebview: ^6.0.0-beta.21
  flutter_keyboard_visibility: ^5.2.0
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.1.1
  font_awesome_flutter: ^10.2.1
  get: ^4.6.5
  google_fonts: ^3.0.1
  intl: ^0.17.0
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: "^0.11.0"
  flutter_gen_runner: ^4.1.6
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.1.6
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/icon_app.png
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_app.png"
  min_sdk_android: 21 

flutter:
  assets:
    - .env
    - assets/images/



  uses-material-design: true
